### ISSUE TITLE
 1.12-1.0.21 crashes dedicated server Forge 1.12 build 2382

### ISSUE THREAD

**Issue by kreezxil** [PrinceOfAmber/Similsax-Transtructors#3]
Notes:
     on startup

crash report:
https://gist.github.com/58f2abe1a7f9409fc5f5522407ad7fb4

fml server latest:
https://gist.github.com/838ac340a4d96c267557166b327ddb37

possibly related: #2

**Comment by Lothrazar** [comment]
Thanks for the reports its very helpful.

This version should fix it https://minecraft.curseforge.com/projects/similsax-transtructors/files/2443577
