### ISSUE TITLE
1.12 item not showing up.

### ISSUE THREAD

**Issue by Geraldeen** [PrinceOfAmber/Similsax-Transtructors#5]
The Transtructors don't show up when I try to craft them. Both the basic and the advanced version are not even craftable. I have Forge installed and the 1.12 Similsax Transtructors mod.

**Comment by Lothrazar** [comment]
I thought that i checked up on this issue tracker every week but i must have missed this.  They are craftable for me in newest 1.12 version the 1.0.22
